-- Snapshot Metamorphysis Restored
-- Date: 2026-09-02 10:39:04

SET FOREIGN_KEY_CHECKS=0;

TRUNCATE TABLE `page`;
INSERT INTO `page` (`id`, `titre`, `slug`, `afficher_menu`, `meta_description`, `is_published`, `afficher_titre`, `fond_blocs_unifie`, `ordre_menu`, `afficher_footer`) VALUES
('23', 'À vous', 'a-qui-sadresse-cette-demarche', '1', NULL, '1', '0', 'pourpre', '3', '0'),
('22', 'À Propos', 'a-propos', '1', NULL, '1', '0', 'pourpre', '2', '0'),
('21', 'L\'Expérience', 'lexperience', '1', NULL, '1', '0', 'olive', '1', '0'),
('20', 'Accueil', 'accueil', '1', NULL, '1', '0', 'pourpre', '0', '0'),
('24', 'Prestations', 'prestations', '1', NULL, '1', '1', 'pourpre', '4', '0'),
('25', 'Mentions Légales & Confidentialité', 'mentions-legales', '0', NULL, '1', '1', 'individuel', '0', '1');

TRUNCATE TABLE `section`;
INSERT INTO `section` (`id`, `ordre`, `disposition`, `media`, `page_id`, `largeur_media`, `hauteur_media`, `updated_at`, `contenu`, `titre`, `balise_html`, `couleur_fond`, `citation`, `citation_pos_x`, `citation_pos_y`, `citation_largeur`, `citation_couleur_fond`, `citation_couleur_texte`, `image_pos_x`, `image_pos_y`, `citation_hauteur_max`, `bouton_texte`, `bouton_lien`, `bouton_style`, `bouton_cible`, `image_superposition`, `image_zindex`, `crop_haut`, `crop_bas`, `crop_gauche`, `crop_droite`, `image_lien`, `decalage_pos_y`, `image_cadre`, `texte_gras`, `image_cadre_couleur`, `sous_titre`, `titre_couleur`, `sous_titre_couleur`, `texte_couleur`, `image_cadre_haut`, `image_cadre_bas`, `image_cadre_gauche`, `image_cadre_droite`, `titre_ligne_decor`, `padding_haut`, `padding_bas`, `padding_gauche`, `padding_droite`, `marge_haut`, `marge_bas`, `alignement_texte`, `hauteur_min`) VALUES
('55', '2', 'texte_centre', NULL, '25', NULL, NULL, NULL, '<h3>1. Données collectées</h3><p>Dans le cadre de la prise de contact, de la gestion de votre compte et de la réservation de séances d\'accompagnement, METAMORPHYSIS est amenée à collecter des informations strictement nécessaires : nom, prénom, adresse e-mail, numéro de téléphone et historique des réservations.</p><h3>2. Finalité des traitements</h3><p>Vos données personnelles sont traitées exclusivement pour assurer la gestion de vos rendez-vous, le suivi de vos accompagnements personnalisés, la facturation et la communication liée à vos séances. Vos données ne sont en aucun cas cédées, louées ou vendues à des tiers.</p><h3>3. Vos droits</h3><p>Conformément au Règlement Général sur la Protection des Données (RGPD), vous disposez d\'un droit d\'accès, de rectification, de suppression et de portabilité de vos données. Vous pouvez exercer ces droits à tout moment en écrivant à : <strong>contact@metamorphysis.fr</strong>.</p>', 'Politique de Confidentialité', 'section', 'olive', NULL, '-10', '-40', '90', 'meta-olive', 'meta-gold', '0', '0', NULL, NULL, NULL, 'gold', '_self', 'standard', '1', '0', '0', '0', '0', NULL, '0', '1', '0', 'plum', 'Protection de vos données personnelles [RGPD]', 'gold-hover', 'ivory', 'ivory', '0', '0', '0', '0', 'apres', '48', '48', '48', '48', '0', '0', 'center', NULL),
('50', '1', 'img_droite', 'canape-taupe-6a7f1ba5a707a642826507.jpg', '23', NULL, NULL, NULL, NULL, 'À QUI S\'ADRESSE CETTE DÉMARCHE', 'h2', 'plum', NULL, '-10', '-40', '90', 'meta-olive', 'meta-gold', '0', '0', NULL, NULL, NULL, 'gold', '_self', 'standard', '1', '0', '0', '0', '0', NULL, '0', '1', '0', 'plum', NULL, 'gold-hover', 'ivory', 'ivory', '0', '0', '0', '0', 'apres', '48', '48', '48', '0', '0', '0', 'center', NULL),
('51', '2', 'grille_colonnes', NULL, '23', NULL, NULL, NULL, NULL, NULL, 'h2', 'olive', NULL, '-10', '-40', '90', 'meta-olive', 'meta-gold', '0', '0', NULL, NULL, NULL, 'gold', '_self', 'standard', '1', '0', '0', '0', '0', NULL, '0', '1', '0', 'plum', NULL, 'gold-hover', 'ivory', 'ivory', '0', '0', '0', '0', 'apres', '48', '48', '48', '48', '-80', '0', 'center', NULL),
('52', '3', 'bandeau_conclusion', NULL, '23', NULL, NULL, NULL, 'Cette démarche demande du courage.\nMais c\'est aussi là que tout commence.', NULL, 'h2', 'none', NULL, '-10', '-40', '90', 'meta-olive', 'meta-gold', '0', '0', NULL, NULL, NULL, 'gold', '_self', 'standard', '1', '0', '0', '0', '0', NULL, '0', '1', '0', 'plum', NULL, 'gold-hover', 'ivory', 'ivory', '0', '0', '0', '0', 'apres', '0', '0', '0', '0', '0', '0', 'center', NULL),
('53', '1', 'slider_prestations', NULL, '24', NULL, NULL, NULL, NULL, 'NOS OFFRES D\'ACCOMPAGNEMENT', 'section', 'plum', NULL, '-10', '-40', '90', 'meta-olive', 'meta-gold', '0', '0', NULL, NULL, NULL, 'gold', '_self', 'standard', '1', '0', '0', '0', '0', NULL, '0', '1', '0', 'plum', 'DES PARCOURS SUR-MESURE ADAPTÉS À VOTRE ÉVOLUTION', 'gold-hover', 'ivory', 'ivory', '0', '0', '0', '0', 'apres', '48', '60', '48', '48', '0', '0', 'center', NULL),
('54', '1', 'texte_centre', NULL, '25', NULL, NULL, NULL, '<h3>1. Éditeur du site</h3><p><strong>METAMORPHYSIS</strong><br>Consultante en relation humaine & Analyse transactionnelle<br>Responsable de la publication : <strong>Louisa CHOUIHI</strong><br>SIRET : En cours d\'immatriculation<br>Contact : contact@metamorphysis.fr</p><h3>2. Hébergement</h3><p>Le site est hébergé par la société <strong>Hostinger International Ltd.</strong><br>61 Lordou Vironos Street, 6023 Larnaca, Chypre<br>Site web : <a href=\"https://www.hostinger.fr\" target=\"_blank\" rel=\"noopener noreferrer\" style=\"color: var(--meta-gold);\">www.hostinger.fr</a></p><h3>3. Propriété intellectuelle</h3><p>L\'ensemble des éléments graphiques, textuels, logos, marques et structures composant ce site sont la propriété exclusive de METAMORPHYSIS et de Louisa CHOUIHI. Toute reproduction, diffusion, modification ou utilisation sans autorisation préalable expresse est strictement interdite.</p>', 'Mentions Légales', 'section', 'olive', NULL, '-10', '-40', '90', 'meta-olive', 'meta-gold', '0', '0', NULL, NULL, NULL, 'gold', '_self', 'standard', '1', '0', '0', '0', '0', NULL, '0', '1', '0', 'plum', 'Éditeur du site & Hébergement', 'gold-hover', 'ivory', 'ivory', '0', '0', '0', '0', 'apres', '48', '48', '48', '48', '0', '0', 'center', NULL),
('49', '1', 'img_droite', 'louisa-presentation.jpg', '22', NULL, NULL, NULL, 'Diplômée et passionnée par l\'humain, j\'accompagne depuis plusieurs années les personnes et les professionnels dans la compréhension de leurs dynamiques intérieures et relationnelles.\n\nÀ travers l\'analyse transactionnelle et une écoute bienveillante mais exigeante, nous explorons ensemble ce qui se joue au-delà des apparences pour déconstruire les croyances limitantes et révéler votre véritable potentiel.', 'CHOUIHI LOUISA', 'h2', 'plum', 'L\'accompagnement Métamorphysis s\'adresse à celles et ceux qui ressentent le besoin d\'éclairer leur trajectoire, de dénouer des blocages profonds et de reprendre les rênes de leur vie avec clarté, authenticité et sérénité.', '15', '-120', '85', 'meta-olive', 'meta-ivory', '0', '0', NULL, NULL, NULL, 'gold', '_self', 'standard', '1', '0', '0', '0', '0', NULL, '0', '1', '0', 'plum', 'CONSULTANTE EN RELATION HUMAINE', 'gold-hover', 'gold-hover', 'ivory', '0', '0', '0', '0', 'apres', '48', '48', '48', '0', '0', '0', 'center', NULL),
('47', '1', 'img_droite', 'vase.jpg', '21', NULL, NULL, NULL, 'Grâce à l\'analyse transactionnelle, nous mettons en lumière les schémas inconscients qui influencent vos relations, vos choix et votre bien-être.\n\nComprendre. Transformer. Se libérer. Redevenir auteur de sa propre vie.', 'L\'EXPÉRIENCE', 'h2', 'olive', NULL, '-10', '-40', '90', 'meta-olive', 'meta-gold', '0', '0', NULL, NULL, NULL, 'gold', '_self', 'standard', '1', '0', '0', '0', '0', NULL, '0', '1', '0', 'plum', '- γνῶθι σεαυτόν - CONNAIS-TOI TOI-MÊME', 'gold-hover', 'ivory', 'ivory', '0', '0', '0', '48', 'apres', '0', '0', '48', '0', '0', '0', 'center', '0'),
('48', '2', 'grille_colonnes', NULL, '21', NULL, NULL, NULL, NULL, 'LE PROCESSUS', 'h2', 'olive', NULL, '-10', '-40', '90', 'meta-olive', 'meta-gold', '0', '0', NULL, NULL, NULL, 'gold', '_self', 'standard', '1', '0', '0', '0', '0', NULL, '0', '1', '0', 'plum', NULL, 'gold-hover', 'ivory', 'ivory', '0', '0', '0', '0', 'apres', '48', '48', '48', '48', '0', '0', 'center', NULL),
('46', '3', 'slider_prestations', NULL, '20', NULL, NULL, NULL, 'Les séances ne sont pas remboursées par la sécurité sociale.', 'Les espaces d\'accompagnement', 'section', 'plum', 'Le rythme et la durée de l\'accompagnement sont définis ensemble lors de la première rencontre, en fonction de vos besoins et de vos objectifs.', '-10', '-40', '90', 'meta-olive', 'meta-gold', '0', '0', NULL, 'En savoir plus', '/prestations', 'gold', '_self', 'standard', '1', '0', '0', '0', '0', NULL, '0', '1', '0', 'plum', 'DIFFÉRENTES MODALITÉS POUR RÉPONDRE À VOS BESOINS', 'gold-hover', 'ivory', 'ivory', '0', '0', '0', '0', 'apres', '48', '60', '48', '48', '0', '0', 'center', NULL),
('45', '2', 'img_droite', 'fauteuils.jpg', '20', NULL, NULL, NULL, 'Certaines personnes viennent avec une problématique précise. D\'autres ressentent simplement qu\'un schéma se répète sans parvenir à l\'expliquer.\n\nLors de la première rencontre, nous prenons le temps de comprendre votre situation afin de définir ensemble le rythme et l\'orientation de l\'accompagnement.', 'Chaque transformation commence par une rencontre.', 'section', 'plum', NULL, '-10', '-40', '90', 'meta-olive', 'meta-gold', '0', '0', NULL, 'PRENDRE RENDEZ-VOUS', '/prestations', 'btn-gold', '_self', 'standard', '1', '0', '0', '0', '0', NULL, '0', '1', '0', 'plum', 'CHAQUE PARCOURS EST UNIQUE', 'gold-hover', 'ivory', 'ivory', '0', '0', '0', '35', 'apres', '48', '48', '48', '48', '0', '0', 'center', NULL),
('44', '1', 'grille_colonnes', NULL, '20', NULL, NULL, NULL, 'Un processus d\'accompagnement sur-mesure en quatre étapes pour vous libérer des schémas limitants.', 'VOTRE CHEMINEMENT VERS LA TRANSFORMATION', 'section', 'plum', NULL, '-10', '-40', '90', 'meta-olive', 'meta-gold', '0', '0', NULL, NULL, NULL, 'gold', '_self', 'standard', '1', '0', '0', '0', '0', NULL, '0', '1', '0', 'plum', 'BIENVENUE CHEZ METAMORPHYSIS', 'gold-hover', 'ivory', 'ivory', '0', '0', '0', '0', 'apres', '60', '48', '48', '48', '0', '0', 'center', NULL),
('56', '3', 'texte_centre', NULL, '25', NULL, NULL, NULL, '<p>Chaque séance d\'accompagnement fait l\'objet d\'une préparation sur-mesure et d\'un créneau horaire strictement réservé à votre attention.</p><p><strong>Délai de prévenance :</strong> Tout report ou annulation de séance doit être formulé au minimum <strong>48 heures à l\'avance</strong> par e-mail ou depuis votre espace personnel.</p><p>En cas d\'annulation tardive (moins de 48h avant le rendez-vous) ou de non-présentation, la séance sera considérée comme due et ne donnera lieu à aucun remboursement, sauf cas de force majeure dûment justifié.</p>', 'Conditions d\'Annulation', 'section', 'olive', NULL, '-10', '-40', '90', 'meta-olive', 'meta-gold', '0', '0', NULL, NULL, NULL, 'gold', '_self', 'standard', '1', '0', '0', '0', '0', NULL, '0', '1', '0', 'plum', 'Modalités relatives aux rendez-vous', 'gold-hover', 'ivory', 'ivory', '0', '0', '0', '0', 'apres', '48', '48', '48', '48', '0', '0', 'center', NULL);

TRUNCATE TABLE `etape`;
INSERT INTO `etape` (`id`, `titre`, `texte`, `icone`, `section_id`) VALUES
('31', 'CETTE DÉMARCHE PEUT VOUS CORRESPONDRE SI...', '· Vous ressentez que les mêmes situations se répètent dans votre vie.\n· Vous avez conscience d\'un problème récurrent que vous n\'arrivez pas à résoudre.\n→ Vous souhaitez comprendre vos schémas relationnels et émotionnels.\n· Vous êtes prêt(e) à un travail de fond et à vous remettre en question.\n→ Vous aspirez à une transformation profonde et durable.', '', '51'),
('30', 'S\'ALIGNER', 'Vivre en cohérence\navec vos valeurs,\nvos besoins\net vos désirs profonds.', 'bi-crosshair', '48'),
('29', 'TRANSFORMER', 'Reprogrammer\nde nouveaux choix,\nalignés avec\nqui vous êtes vraiment.', 'libellule.svg', '48'),
('28', 'CONFRONTER', 'Accueillir la vérité,\nsortir des mécanismes\nde protection\net d\'évitement.', 'bi-symmetry-vertical', '48'),
('40', 'S\'ALIGNER', 'Retrouver une cohérence intérieure et avancer avec plus de liberté et de sens.', 'bi-brightness-high', '44'),
('26', 'OBSERVER', 'Prendre conscience\nde ses schémas\net fonctionnements\nrépétitifs.', 'bi-eye', '48'),
('27', 'COMPRENDRE', 'Identifier les origines,\nles blessures et les\nmessages cachés\nderrière les comportements.', 'bi-brain', '48'),
('37', 'OBSERVER', 'Prendre conscience de ce qui se répète et de ses impacts.', 'bi-eye', '44'),
('38', 'COMPRENDRE', 'Mettre en lumière les mécanismes inconscients qui influencent vos choix.', 'bi-brain', '44'),
('32', 'CETTE DÉMARCHE NE VOUS CONVIENDRA PROBABLEMENT PAS SI...', '· Vous cherchez des solutions rapides ou toutes faites.\n→ Vous attendez que quelqu\'un d\'autre change à votre place.\n· Vous n\'êtes pas prêt(e) à regarder ce qui gêne.\n→ Vous refusez toute remise en question.\n→ Vous préférez rester dans vos certitudes.', '', '51'),
('39', 'TRANSFORMER', 'Construire de nouvelles réponses et sortir des schémas limitants.', 'bi-flower1', '44');

TRUNCATE TABLE `prestation`;
INSERT INTO `prestation` (`id`, `nom`, `description`, `prix`, `duree`, `image_name`, `updated_at`, `est_mis_en_avant`, `icone`, `unite_prix`, `ordre`, `description_complementaire`, `lien_video`, `nombre_seances`) VALUES
('10', 'Séance Individuelle (Analyse Transactionnelle)', 'Exploration en profondeur d\'une problématique ciblée, mise en lumière des états du moi et déconstruction des scénarios répétitifs.', '80', '60', NULL, NULL, '1', 'bi-person', NULL, '2', NULL, NULL, '1'),
('9', 'Consultation Initiale', 'Un premier diagnostic complet pour cibler vos besoins, explorer vos attentes et définir ensemble une stratégie d\'évolution et d\'accompagnement sur-mesure.', '50', '45', NULL, NULL, '1', 'bi-person', NULL, '1', NULL, NULL, '1'),
('11', 'Bilan Émotionnel & Relationnel', 'Cartographie complète de vos dynamiques intérieures, analyse de vos mécanismes de défense et identification des blocages profonds.', '120', '90', NULL, NULL, '0', 'bi-diagram-3', NULL, '3', NULL, NULL, '1'),
('12', 'Suivi Mensuel', 'Un accompagnement régulier avec des points d\'étape hebdomadaires, des exercices d\'alignement et des ajustements continus.', '150', '120', NULL, NULL, '0', 'bi-people', NULL, '4', NULL, NULL, '2'),
('13', 'Parcours Renaissance (3 Mois)', 'Un programme structuré de transformation personnelle sur 3 mois pour vous libérer des schémas limitants et ancrer durablement vos nouveaux choix.', '390', '180', NULL, NULL, '1', 'bi-diagram-3', NULL, '5', NULL, NULL, '3'),
('14', 'Pack Métamorphose', 'La refonte totale de votre approche de vie. Inclut un suivi intensif prioritaire, bilans personnalisés et accompagnement immersif.', '450', '300', NULL, NULL, '1', 'bi-house-heart', NULL, '6', NULL, NULL, '5');

TRUNCATE TABLE `section_prestation`;
INSERT INTO `section_prestation` (`section_id`, `prestation_id`) VALUES
('46', '9'),
('46', '10'),
('46', '11'),
('46', '12'),
('46', '13'),
('46', '14'),
('53', '9'),
('53', '10'),
('53', '11'),
('53', '12'),
('53', '13'),
('53', '14');

TRUNCATE TABLE `user`;
INSERT INTO `user` (`id`, `email`, `roles`, `password`, `prenom`, `nom`, `telephone`) VALUES
('6', 'artas971@gmail.com', '[\"ROLE_ADMIN\", \"ROLE_USER\"]', '$2y$13$yj744CfO5wQQpb/Da50jae7QnKIDF/tubxntcpVJfno6TGTn21ur.', 'Admin', 'Metamorphysis', NULL);

SET FOREIGN_KEY_CHECKS=1;
