# config/services.yaml
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $dailyApiKey: '%env(DAILY_API_KEY)%'

    App\:
        resource: '../src/'

    App\Service\EncryptionService:
        arguments:
            $encryptionKey: '%env(ENCRYPTION_KEY)%'

    App\Service\DailyCoService: {}